### ISSUE TITLE
To-Do List: Improvements

### ISSUE THREAD

**Issue by KrishnanN27** [KrishnanN27/KrishnanN27.github.io#1]
- [ ] Find a way to host the portfolio upon committing changes.
- [ ] Add professional pictures.
- [ ] Add links to the project section.
- [ ] Work on the UI for the entire portfolio.
- [ ] Add more gallery images (but address the image size issue).
- [ ] Add a download CV and cover letter button.
